//state de productos

export const OBTENER_PRODUCTOS_EXITO = "OBTENER_PRODUCTOS_EXITO";

// state de pedido

export const SELECCIONAR_PRODUCTO = "SELECCIONAR_PRODUCTO";

export const CONFIRMAR_ORDENAR_PLATO = "CONFIRMAR_ORDENAR_PLATO";

export const MOSTRAR_RESUMEN = "MOSTRAR_RESUMEN";
